services:
  zookeeper:
    image: zookeeper:3.9
    container_name: solr-zk
    # restart: always
    ports:
      - "2181:2181"
    networks:
      - apache-solr_default

  solr:
    build: .
    container_name: ranger-solr
    depends_on:
      - zookeeper
    environment:
      SOLR_OPTS: "-DzkHost=zookeeper:2181"
    command: bash -c "solr-foreground -c & /opt/solr-tools/init-solr.sh && wait"
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
      - ./solr-config:/opt/solr-config:ro


volumes:
  solr-data:

networks:
  apache-solr_default:
    name: apache-solr_default  # This forces the name to be EXACTLY this
    driver: bridge