services:
  solr:
    image: solr:9.6.1
    container_name: ranger-solr
    restart: always
    environment:
      SOLR_USER: ${SOLR_USER}
      SOLR_PASS: ${SOLR_PASS}
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr
      - ./generate-security.sh:/solr-init/generate-security.sh
      - ./.env:/solr-init/.env 
    command: >
      bash -c "solr-precreate ranger_audits && bash /solr-init/generate-security.sh && solr start -f"
