version: "3.8"

services:
  solr:
    image: solr:9.6.1
    container_name: ranger-solr
    restart: always
    environment:
      - SOLR_HOME=/var/solr/data
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr
    command:
      - solr-precreate
      - ranger_audits
