
services:
  zookeeper:
    image: zookeeper:3.9
    container_name: solr-zk
    restart: always
    ports:
      - "2181:2181"
  solr:
    build: ./solr
    container_name: ranger-solr
    depends_on:
      - zookeeper
    environment:
      SOLR_OPTS: "-DzkHost=zookeeper:2181"
    command: solr-foreground -c
    restart: always
    env_file:
      - ./.env
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
      - ./solr-config:/opt/solr-config:ro
volumes:
  solr-data:
