
services:
  solr:
    build: .
    container_name: ranger-solr
    restart: always
    env_file:
      - ./.env
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
volumes:
  solr-data:
